### PR TITLE
feat: add html2ps

### PR DESCRIPTION
**Pull request by Diamond-Fur**
This program converts HTML directly to PostScript. The HTML code can be retrieved from one or more URLs or local files, specified as parameters on the command line.

Log: add html2ps
Issue: github.com/deepin-community/sig-deepin-sysdev-team/issues/73

### CODE REVIEW

**Comment by Zeno-sole** [comment]
debian/control用的还是模板 检查一下

**Comment by Zeno-sole** [comment]
patch 打失败了，检查一下是否pop了

**Comment by Diamond-Fur** [comment]
@chenchongbiao

**Comment by Diamond-Fur** [comment]
> patch 打失败了，检查一下是否pop了

已经修改完毕

**Pull request merged**
